#!/bin/sh


if [ $# -gt 1 ]
	then echo tobb parametert adott meg
elif [ $(echo $1 | grep [a-z,A-Z] | wc -w) -gt 0 ]
	then echo Kerem szamot adjon meg
elif [ $1 -lt 0 ]
	then echo Kerem ne adjon meg negativ szamot
else
	i=$1
	fakt=1
	while [ $i -gt 1 ]
	do
		fakt=$(expr $fakt \* $i)
		i=$(expr $i - 1)
	done
	echo a $1 szam faktorialisa :  $fakt
fi