#!/bin/bash
atfogo=$1
befogo=$2
if [ $# -gt 2 ]
then 
	echo Tobb mint 2 parametert adott meg!
else
	if [ $# -lt 1 ]
	then
		echo -n "Kerem az atfogo erteket: "
		read atfogo
	fi
	if [ $# -lt 2 ]
	then 
		echo -n "Kerem a befogo erteket: "
		read befogo
	fi
	echo "A masik befogo hosszanak negyzete ($atfogo*$atfogo -$befogo*$befogo)=" $(expr $atfogo \* $atfogo - $befogo \* $befogo)
fi