#!/bin/sh

szam=$1
if [ $szam -lt 0 ]
then 
	szam=$(expr $szam \* -1)
fi

szamjegy=$(expr $(echo $szam | wc -m) - 1)

if [ $szamjegy -eq 1 ]
then
	echo egyjegyu
elif [ $szamjegy -eq 2 ]
then
	echo ketjegyu
elif [ $szamjegy -eq 3 ]
then
	echo haromjegyu
else
	echo tobb mint haromjegyu
fi

#-l sor
#-c byte
#-m karakterek
#-w szavak